---
title: "0219_meeting0_summary"
author: "Xinyao Wu"
date: "2/19/2020"
output: 
  html_document: 
    number_sections: false
    code_folding: hide
    toc: true
    toc_float: true
---

#Review & Summarize
###1.	What is positivity violation?

To identify the Actual causal Effect(ACE), 4 assumptions need to be satisfied, and positivity is one of them. It means if __P(A=a|C=c)is positive for all C such that P(C=c) is nonzero__ does not hold, ACE cannot be identified so it is meaningless to calculate the "formula" ACE.

###2.	What is the difference between $E[Y_{e_(75th)} - Y_{e^*_25th}]$ and $E[Y_{g(A)}-Y_{g(A)^*}]$

Since it is a multi-exporsure analysis, we specify it as one metal first.
$E[Y_{e_(75th)} - Y_{e^*_25th}]$ means using descriptive characteristics (eg.75 percentile,25 percentile) to estimate the causal effect.
$E[Y_{g(A)}-Y_{g(A)^*}]$ means using different distributions when estimating the causal effect.

###3.	What does E[A|C] mean? Why 

It means the average of A under the condition of C. It also means for this project we generate C first, specify it as a known factor. For generating A, the random effect would not come until the average has been generated. 

###4.	How to generate E[A|C]?



$$
E[A|C]=\left\{
\begin{aligned}

 \beta_0^{A_1}+\beta_2^{A_1}*C \\
 \beta_0^{A_2}+\beta_2^{A_2}*C \\
 \beta_0^{A_3}+\beta_2^{A_3}*C 

\end{aligned}
\right.
$$


*Notify that there is a correlation matrix in the paper need to be applied*


###5.	What is the DAG of this study after simplifying?


###6.	What’s the structure relationship between sample size, simulation size and bootstrap size ?

*The difference between bootstrap and simulation*

Bootstrap is a nun-parametric way for simulating from an unknown distribution. 
The reason why this project needs both bootstrap and simulation is that we use simulation to generate data, then use bootstrap to sample from 'observed data' to do the checking things(like accuracy, misclassification rate or ect.)

###7.	What does it means to utilize linear regression to fit E[Y|A,C]?

$$E[Y|A,C] = \beta_0 +\beta_1A+\beta_2C$$
only when Assuming A and C are independent, the formula above can hold.
If we pretend not knowing the generation process and assume A and C are independent, this process would be the first step for a normal analysis pipeline. So we do this step to get a general idea of the effect from falsl modeling.

###8.	What is Marginal Structure Model? 

$$E[Y_a]=\beta_0+\beta_1A$$
Above is MSM

To let this formula make sense, each observed point needs to be weighted according to the joint distribution of A and C.

###9.	How to fit MSM? What will be solved after fitting MSM?
 
(1) Calculate IPTW

(2) Weight each data point

(3) Build marginal model


#Coding & Tasks

##1.Objective

###(1)specify a case for showing $E[Y_{g(A)}-Y_{g(A)^*}]$

referring 2 in the review:


###(2)Simulation


##2.Explanation




#Prospective 









