---
title: "0227 code"
author: "Xinyao Wu"
date: "2/27/2020"
output: 
    html_document:
    number_sections: false
    code_folding: hide
    toc: True
    toc_float: True
    theme: lumen
      
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(MASS)
library(twang)
library(CBPS)
```

## ACE calculation function(regression)
```{r regression}
re.est = function(df,n){
### Method1. Regression 
  
fit = lm(cs~as+mn+pb+age*iq+as.factor(edu)*iq+as.factor(smoke)^2,data = df)

obs = df[4:7]
as = pull(df,as)
mn = pull(df,mn)
pb = pull(df,pb)

as.q = quantile(as,c(0.25,0.75))
mn.q = quantile(mn,c(0.25,0.75))
pb.q = quantile(pb,c(0.25,0.75))

as = rep(as.q[1],n)
mn = rep(mn.q[1],n)
pb = rep(pb.q[1],n)
new1 = data.frame(as,mn,pb,obs)
yhat_25 = predict(fit,new1,type = 'response')

as = rep(as.q[2],n)
mn = rep(mn.q[2],n)
pb = rep(pb.q[2],n)
new2 = data.frame(as,mn,pb,obs)
yhat_75 = predict(fit,new2,type = 'response')

ace = mean(yhat_75)-mean(yhat_25)


return(ace)
}
```

###Method2. MSM(function)

[IPW reference](https://meghapsimatrix.com/post/continuous-r-rmarkdown/)

```{r}

ipw = function(x,df,form){
# the numerator
mod_num <- lm(x ~ 1, data = df)

num <- dnorm(x = x, # treatment 
             mean = fitted.values(mod_num), # fitted values
             sd = summary(mod_num)$sigma) # model sigma
# the demonimator
mod_den <- lm(formula = form, data = df)

den <- dnorm(x = x, # treatment variable
             mean = fitted.values(mod_den), # fitted values
             sd = summary(mod_den)$sigma)
ipw_s = num/den
return(ipw_s)
}

```

##Simulation
```{r}
n=825
#simulation = 100
nsim = 100
est.holder = rep(NA,nsim)
true.holder = rep(NA,nsim)
for(i in 1:nsim){
#confoundings
age = rnorm(825,22.9,4.2)
iq = rnorm(825,26,5)
edu = rbinom(825,1,0.24)
smoke = rbinom(825,1,0.8)
obs = data.frame(age,iq,edu,smoke)
#a
as = age*2+age*iq+edu+smoke^2+rnorm(825,0,0.5)
mn = 0.63*as+age*2+edu^2+iq+smoke^3+rnorm(825,0,0.5)
pb = 0.28*mn+age+iq+edu+smoke+rnorm(825,0,0.5)
#y
cs = 0.05*as+0.7*mn-0.023*pb+age*iq+edu*iq+smoke^2 +rnorm(n,sd = 0.23)
df = data.frame(as,mn,pb,obs,cs)
#true ace
true.holder[i] = 0.05*(quantile(as,0.75)-quantile(as,0.25))+0.7*(quantile(mn,0.75)-quantile(mn,0.25))-0.023*(quantile(pb,0.75)-quantile(pb,0.25))
est.holder[i] = re.est(df,n = n)
}

bias = est.holder-true.holder
hist(bias)
```

## Marginal Structure Model

```{r}
#test
form1 = 'as~age+iq+as.factor(edu)+as.factor(smoke)'
form2 = 'mn~as+age+iq+as.factor(edu)+as.factor(smoke)'
form3 = 'pb~as+age+iq+as.factor(edu)+as.factor(smoke)'
asw = ipw(as,df,form1)
mnw = ipw(mn,df,form2)
pbw = ipw(pb,df,form3)

#weight matrix
weight.matrix = asw*mnw*pbw
msm <-svyglm(cs~as+mn+pb,design = svydesign(~ 1, weights = ~ weight.matrix,data=df))
coef(msm)
```

#description
```{r}

var(est.holder)
var(true.holder)
hist(est.holder)
```


##Bootstrap

```{r}

# boots = 100
# b.holder = rep(NA)
# for (i in 1:boots) {
#   
#   idx = sample(1:n,size = n, replace = TRUE)
#   data.b = df[idx,]
# 
# quantile(as.b,0.25)
# 
# b.holder[i] = re.est(df = data.b,n = n)
# }
# 
# var(b.holder)
```

